### ISSUE TITLE
Install LangSim locally

### ISSUE THREAD

**Issue by jan-janssen** [jan-janssen/LangSim#54]
There are currently different ways to install `LangSim` locally:
```
git clone https://github.com/jan-janssen/LangSim
cd LangSim
conda env create -f environment.yml --name LangSim
```

Currently, the code requires `pymace` which is not included in the `environment.yml`, it can be installed using:
```
conda install -c conda-forge pymace
```

Afterwards you can either install the `LangSim` package locally:
```
pip install .
```
Alternatively, if you do not want to install the package you can either set the python path:
```
export PYTHONPATH="/path/to/LangSimRepository":$PYTHONPATH
```
Or you execute the tests directly in the repository folder, in that case you have to copy the `demonstration.ipynb` notebook from the `notebooks` folder:
```
mv notebooks/demonstration.ipynb . 
```

**Comment by Bernadette-Mohr** [comment]
I encountered a minor issue that I don't remember seeing in the remote version:
```
langchain ValueError: An output parsing error occurred. In order to pass this error back to the agent and have it try again, pass `handle_parsing_errors=True` to the AgentExecutor. This is the error: Could not parse tool input: {'arguments': '{\n"atom_dict": {\n "numbers": [47],\n "positions": [[0.0, 0.0, 0.0]],\n "cell": [[0.0, 2.045, 2.045], [2.045, 0.0, 2.045], [2.045, 2.045, 0.0]],\n "pbc": [True, True, True]\n},\n"calculator_str": "emt"\n}', 'name': 'get_atom_dict_equilibrated_structure'} because the `arguments` is not valid JSON.
```

It's easy enough to fix by setting `handle_parsing_errors=True` when initializing the `AgentExecutor` in `llm.py, line 70.

**Comment by jan-janssen** [comment]
Does this happen with ChatGPT 4? I remember I had a similar issue with 4 but not with 4o.

**Comment by jan-janssen** [comment]
The installation instructions are now also included in the website.
